#!/usr/bin/env bash

####
#### USAGE section
####

function usage {
cat << EOF
###### ###### ###### ###### ###### ###### ###### ###### ##### ##### #####

gcctx: \`gcloud config configurations\` manipurator.

syntax: see https://github.com/ykamenashi/gcctx/blob/master/README.md 

###### ###### ###### ###### ###### ###### ###### ###### ##### ##### #####
EOF
  exit 0
}

if [ $# -lt 1 ]; then
  usage
fi 

###
### GET section
###
function get {
  LIST_COMMAND="$BASE_COMMAND list"
  $LIST_COMMAND
}

###
### menu definitions
###
SUPPORTED_ACTIONS="GET COPY SELECT MOVE"
BASE_COMMAND="gcloud config configurations"

case $1 in
g)
  get
  ;;
c)
  ;;
s)
  ;;
m)
  ;;
*)
  usage
  ;;
esac
